### PR TITLE
Update Key.d.ts to fix build

### PR DESCRIPTION
**Pull request by nikhilag**
## Change Summary
I ran into a build issue on using latest typesense library because of the typescript issue in Key.d.ts file.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Review by jasonbosco — APPROVED** [review]

**Comment by jasonbosco** [comment]
Hmm wonder how Typescript compilation didn't catch that. 

Thank you for the PR!

**Comment by jasonbosco** [comment]
Oh wait, this change is in the compiled JS code in the `/lib` folder. This needs to be added in the corresponding file in `src`.

**Comment by nikhilag** [comment]
> Oh wait, this change is in the compiled JS code in the `/lib` folder which will get overridden on build. So this needs to be added in the corresponding .ts file in `src`.
> 
> Could you update the PR?

Yes doing this now

**Review by jasonbosco — CHANGES_REQUESTED** [review]
This change is in the compiled JS code in the /lib folder which will get overridden on build. So this needs to be added in the corresponding .ts file in src.

Could you update the PR?

**Comment by nikhilag** [comment]
@jasonbosco It seems `value_prefix?: string;` was missing from Key.ts file under src. I have now added it there. Please check if this works. Locally building the code is adding more changes and so I have done these changes in github directly.

**Review by jasonbosco — APPROVED** [review]
Looks good!

**Comment by jasonbosco** [comment]
Just published this in `v1.7.1`. Thanks @nikhilag!

**Pull request merged**
