### PR TITLE
adds cache clearing functionality

### PR DESCRIPTION
**Pull request by uncvrd**
## Change Summary
This PR exposes a new method, `clearCache` on `SearchClient` which allows for a user to programmatically clear the Typesense client cache. Which is useful for having instant access to new documents after mutations.

To do this, I had to create a method to reset the cache in `RequestWithCache` and then "bubble up" this method through `Multisearch` and `SearchOnlyDocuments` to finally expose it in the `SearchClient` class. Alternatively it might be nice to instantiate the cache at the `SearchClient` level to pass it down, but I didn't want to mess with current implementations.

To clear cache, multisearch is straight forward but with individual collections, we must loop through all collections to reset.

I also added two tests to `SearchClient`, which confirm that the cache is being reset properly, but I'm not sure this is the best location or implementation for them.

Hope this helps or gets us in the right direction!

## PR Checklist

- [ x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by jasonbosco** [comment]
Thank you @uncvrd!

**Comment by uncvrd** [comment]
of course - happy to help!

**Comment by jasonbosco** [comment]
I've published this in v1.4.1-0. Could you give it a shot?

**Comment by uncvrd** [comment]
@jasonbosco Def! I can confirm that this works for my use case!

**Pull request merged**
